* Цели и описание проекта
  Это уже наверное третья попытка проработать цели. Ну ничего, на этот раз уже будет реализация:)
  Суть в том, чтобы дать простой, визуально понятный и главное запоминающийся механизм хранения разнородной
  информации. Так чтобы человек мог как в реальной жизни запоминать где что хранится и работать с данными
  тоже единообразным образом. То есть одним и тем же набором инструметов совершать различные действия. В
  жизни мы делаем это руками, глазами и тд. Вот и работать с информацией нужно одним набором инструментов, а не
  с помощью тысячи и одной программ.
  Но сказать просто, а вот сделать сложнее.

* Как работает, из чего состоит.

  Пользователь попадает на пустой холст. На который может нанести:
  + изображение
  + текст
  + объект
    Объект обязательно принадлежит какому-то типу. Тип либо создаётся вновь, либо выбирается из существующих.
    Объекты одного типа отображаются в одном слое. Это позволяет выбрать только те типы объектов, которые хотите
    видеть. Например у вас карта города и вы хотите видеть только остановки транспорта. Выбираете отображение только
    остановок транспорта. Никакие другие объекты, вроде магазинов, заправок и прочего не отображаются.

   Допустим пользователь создаёт объект дорога и наносит такой объект на холст. Затем создаёт объект остановка и наносит
   два таких объекта вдоль дороги. Теперь он может выбрать в режиме отображения что отображать: 
   + дороги
   + остановки
   + дороги и остановки.
   
   Дальше он может кликнуть на одну из остановок и перед ним откроется чистый холст. На него он может нанести
   всё что знает о остановке, прикрепить фотографии и прочее. Затем проделать то же с другой остановкой.
   Конечно можно и кликнуть на дорогу. На появившемся новеньком холсте нанести всё что нужно знать об этой
   дороге. 

   Таким образом образом пользователь создал два новых типа объекта:
   + дорога
   + остановка
   
   Их можно посмотреть на панеле доступных объектов. Там объекты разделены на две группы:
   + все. То есть вообще все когда-либо созданные пользователями
   + те что используются вместе с тем типом объекта, на холсте которого вы находитесь.
     Например: на холсте объекта карта будут доступны остановки, дороги и прочее. А на холсте музыкального альбома -
     песни, клипы, автор и тд.

   Сами две это группы это холсты, а это значит что все объекты вы можете располагать как пожелаете. Также вы
   можете кликнуть на любой и в появившемся новом холсте добавить например описание типа объекта. Вы можете
   пойти дальше и присвоить объектам тип, заранее создав его. Так вы сможете настроить какие объекты отображать,
   а какие нет.

   В общем с помощью одних и тех же инструментов вы можете создавать объекты, описывать их с помощью других объектов
   и тд.

* где всё хранится
  Может быть несколько вариантов:
  + у вас на устройстве просто как набор файлов
  + в распределённой системе caravan, среди участников
  + в тех доступных хранилищах(скажем dropbox), для которых есть адаптеры
